services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: sms
      POSTGRES_USER: sms
      POSTGRES_PASSWORD: sms
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: {}
